name: Daily MoneyForward import

on:
  workflow_dispatch:          # 手動実行
  schedule:
    - cron:  '0 0 * * *'      # 毎日 09:00 JST

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Python 3.12 をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3) 依存ライブラリをインストール
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps
          sudo apt-get update && sudo apt-get install -y jq

      # 4) 対象年月を計算（⇨ GITHUB_OUTPUT で渡す）
      - name: Compute target year & month
        id: yymm
        run: |
          echo "year=$(date -u +'%Y')"   >> $GITHUB_OUTPUT   # 例: 2025
          echo "month=$(date -u +'%m')"  >> $GITHUB_OUTPUT   # 例: 05

      # 5) インポーターを実行
      - name: Run importer
        env:
          MF_EMAIL:          ${{ secrets.MF_EMAIL }}
          MF_PASSWORD:       ${{ secrets.MF_PASSWORD }}
          MF_STORAGE_B64:    ${{ secrets.MF_STORAGE_B64 }}
          YEAR:              ${{ steps.yymm.outputs.year }}
          MONTH:             ${{ steps.yymm.outputs.month }}
        run: |
          python -m src.main
