name: Daily MoneyForward import

on:
  workflow_dispatch:          # 手動実行
  schedule:
    - cron:  '0 0 * * *'      # 毎日 09:00 JST

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4

      # …（他のセットアップ／依存関係インストールなどのステップ）…

      # 実行年月を取得
      - name: Get year/month
        id: yymm
        run: |
          echo "year=$(date -u +'%Y')"   >> $GITHUB_OUTPUT   # 例: 2025
          echo "month=$(date -u +'%m')"  >> $GITHUB_OUTPUT   # 例: 05

      # 5) インポーターを実行
      - name: Run importer
        env:
          MF_EMAIL:       ${{ secrets.MF_EMAIL }}
          MF_PASSWORD:    ${{ secrets.MF_PASSWORD }}
          MF_STORAGE_B64: ${{ secrets.MF_STORAGE_B64 }}
          YEAR:           ${{ steps.yymm.outputs.year }}
          MONTH:          ${{ steps.yymm.outputs.month }}
        run: |
          python -m src.main || true

      # 6) エラー時にスクリーンショットをアップロード
      - name: Upload login screenshot
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: login-screenshot
          path: login_issue.png
